In [1]:
import os
import numpy as np

In [2]:
def readr(file):
    l1=[]
    l2=[]
    with open(file) as f:
        for i in f:
            xi=i.split()
            l1.append(xi[1])
            l2.append(float(xi[2]))
    return l1,l2

In [3]:
def list_subfolders(dir_path):
    subfolders = []
    for root, dirs, files in os.walk(dir_path):
        for dir_name in dirs:
            subfolders.append(os.path.join(root, dir_name))
    return subfolders

namel=list_subfolders('./process_pdb/')
print(namel[0])

./process_pdb/4DNJ_A


In [4]:
def getnel():
    nel=[]
    with open("noerr.txt") as f:
        for i in f:
            nel.append(i.rstrip())
    return nel
noerrlist=getnel()

In [5]:
hbnam=[]
dl={}
num=0
for i in namel:
    rp=i+'/rec.pdb'
    lp=i+'/lig.pdb'
    if rp not in noerrlist:
        continue
    # print(rp,lp)
    # hbp=i+'/hb.pdb'
    # hb(rp,lp,hbp)
    hbnam.append(i)
    dl[i]=num
    num=num+1
print(len(hbnam),num)

1179 1179


In [6]:
dis=np.zeros((1179, 1179))
for i in range(len(hbnam)):
    path=hbnam[i]+'/result.txt'
    ro,do=readr(path)
    for j in range(len(hbnam)):
        if j<i:
            dis[i][j]=dis[j][i]
        if j>i:
            dis[i][j]=do[j]
print(dis)

[[0.         1.06344351 1.44684711 ... 1.05171341 1.92463704 0.99442701]
 [1.06344351 0.         1.79152045 ... 1.56999589 1.89529896 1.14307771]
 [1.44684711 1.79152045 0.         ... 1.38879644 1.36511356 1.49404507]
 ...
 [1.05171341 1.56999589 1.38879644 ... 0.         2.07463568 1.53784051]
 [1.92463704 1.89529896 1.36511356 ... 2.07463568 0.         1.91927511]
 [0.99442701 1.14307771 1.49404507 ... 1.53784051 1.91927511 0.        ]]


In [7]:
def readf(file):
    tem=[]
    res=[]
    with open(file) as f:
        for i in f:
            xi=i.split()
            tem.append(xi[0])
            crash=float(xi[3])
            fes=float(xi[4])+1.66
            if crash==0 and fes>=1.93 and fes<=2.77:
                res.append(1)
            else:
                res.append(0)
    return tem,res

In [32]:
teml=[]
resl=[]
for i in range(1000):
    path='./exampleall/TM_sup'+str(i)
    f=path+'/scorelist.txt'
    tem,res=readf(f)
    teml.append(tem)
    resl.append(res)

In [33]:
print(resl[0],len(resl[1]))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [34]:
print(len(hbnam),len(teml[2]))
for i in range(len(hbnam)):
    print(i,hbnam[i],teml[1][i],resl[1][i])
    if hbnam[i]+'/rec.pdb'!=teml[1][i]:
        print(i)
        break

1179 1178
0 ./process_pdb/4DNJ_A ./process_pdb/4DNJ_A/rec.pdb 0
1 ./process_pdb/4L49_A ./process_pdb/4L49_A/rec.pdb 0
2 ./process_pdb/3DL9_A ./process_pdb/3DL9_A/rec.pdb 0
3 ./process_pdb/5HS1_A ./process_pdb/5HS1_A/rec.pdb 0
4 ./process_pdb/1E9X_A ./process_pdb/1E9X_A/rec.pdb 0
5 ./process_pdb/4G48_A ./process_pdb/4G48_A/rec.pdb 0
6 ./process_pdb/1PHC_A ./process_pdb/1PHC_A/rec.pdb 0
7 ./process_pdb/4C9P_A ./process_pdb/4C9P_A/rec.pdb 0
8 ./process_pdb/7SHI_A ./process_pdb/7SHI_A/rec.pdb 0
9 ./process_pdb/3IW2_A ./process_pdb/3IW2_A/rec.pdb 0
10 ./process_pdb/1CMJ_A ./process_pdb/1CMJ_A/rec.pdb 0
11 ./process_pdb/4I91_A ./process_pdb/4I91_A/rec.pdb 0
12 ./process_pdb/6DA2_A ./process_pdb/6DA2_A/rec.pdb 0
13 ./process_pdb/7RKW_A ./process_pdb/7RKW_A/rec.pdb 0
14 ./process_pdb/4PXH_A ./process_pdb/4PXH_A/rec.pdb 0
15 ./process_pdb/4L4D_A ./process_pdb/4L4D_A/rec.pdb 0
16 ./process_pdb/7KVH_A ./process_pdb/7KVH_A/rec.pdb 0
17 ./process_pdb/6CIR_A ./process_pdb/6CIR_A/rec.pdb 0
18 ./proce

In [35]:
for i in range(len(hbnam)-1):
    print(i,hbnam[i],teml[1][i])
    if i>862:
        print(i,hbnam[i+1],teml[1][i])
    else:
        print(i,hbnam[i],teml[1][i])

0 ./process_pdb/4DNJ_A ./process_pdb/4DNJ_A/rec.pdb
0 ./process_pdb/4DNJ_A ./process_pdb/4DNJ_A/rec.pdb
1 ./process_pdb/4L49_A ./process_pdb/4L49_A/rec.pdb
1 ./process_pdb/4L49_A ./process_pdb/4L49_A/rec.pdb
2 ./process_pdb/3DL9_A ./process_pdb/3DL9_A/rec.pdb
2 ./process_pdb/3DL9_A ./process_pdb/3DL9_A/rec.pdb
3 ./process_pdb/5HS1_A ./process_pdb/5HS1_A/rec.pdb
3 ./process_pdb/5HS1_A ./process_pdb/5HS1_A/rec.pdb
4 ./process_pdb/1E9X_A ./process_pdb/1E9X_A/rec.pdb
4 ./process_pdb/1E9X_A ./process_pdb/1E9X_A/rec.pdb
5 ./process_pdb/4G48_A ./process_pdb/4G48_A/rec.pdb
5 ./process_pdb/4G48_A ./process_pdb/4G48_A/rec.pdb
6 ./process_pdb/1PHC_A ./process_pdb/1PHC_A/rec.pdb
6 ./process_pdb/1PHC_A ./process_pdb/1PHC_A/rec.pdb
7 ./process_pdb/4C9P_A ./process_pdb/4C9P_A/rec.pdb
7 ./process_pdb/4C9P_A ./process_pdb/4C9P_A/rec.pdb
8 ./process_pdb/7SHI_A ./process_pdb/7SHI_A/rec.pdb
8 ./process_pdb/7SHI_A ./process_pdb/7SHI_A/rec.pdb
9 ./process_pdb/3IW2_A ./process_pdb/3IW2_A/rec.pdb
9 ./process_

In [36]:
def cksuc(zx):
    suc=0
    #print(zx)
    for i in range(len(teml)):
        for j in zx:
            if j==862 or j==1178:
                continue
            if j>862:
                j=j-1
            #print(i,j,len(resl[i]))
            if resl[i][j]==1:
                suc=suc+1
                break
    return suc/1000

In [37]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from scipy.spatial.distance import squareform

from scipy.spatial.distance import pdist, squareform

distance_matrix = dis

# 计算每个类的中位数点（Medoid）
def zx(labels):
    medoids = []
    for label in np.unique(labels):
        class_indices = np.where(labels == label)[0]
        class_distances = distance_matrix[np.ix_(class_indices, class_indices)]
        medoid_index = class_indices[np.argmin(class_distances.sum(axis=1))]
        medoids.append(medoid_index)
    return medoids



# 将距离矩阵转换为压缩的距离向量
condensed_distance_matrix = squareform(distance_matrix)

# 计算层次聚类的连接矩阵
Z = linkage(condensed_distance_matrix, method='complete')

for i in range(1,31):
    labi = fcluster(Z, i*0.1, criterion='distance')
    zxl=zx(labi)
    suc=cksuc(zxl)
    print(i,len(zxl),suc)

1 1087 0.883
2 805 0.883
3 587 0.883
4 451 0.881
5 354 0.88
6 272 0.879
7 205 0.878
8 164 0.876
9 128 0.875
10 101 0.875
11 75 0.872
12 62 0.865
13 49 0.864
14 43 0.863
15 33 0.857
16 29 0.851
17 23 0.838
18 20 0.835
19 19 0.831
20 16 0.819
21 16 0.819
22 14 0.806
23 12 0.792
24 11 0.78
25 11 0.78
26 10 0.771
27 8 0.737
28 8 0.737
29 7 0.712
30 5 0.682
